-- Up
CREATE TABLE User (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    email TEXT
)

CREATE TABLE Home (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    
)

CREATE TABLE Cat (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    ownerId INTEGER FOREIGN KEY REFERENCES User(id)
)
--Down
DROP TABLE User;
DROP TABLE Home;
DROP TABLE Cat;

